let state={config:{},whitelist:[],tasks:[],followups:[],channels:[]};
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const v=await r.json();if(!r.ok)throw Error(v.error||'操作失败');return v}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
async function load(){state=await api('/api/state');render()}
function render(){
  $('#greeting').textContent=`你好，${state.config.ownerName||''}`; $('#mFollowups').textContent=state.followups.filter(x=>x.status!=='已关闭').length; $('#mTasks').textContent=state.tasks.filter(x=>x.status!=='已完成').length; $('#mWhite').textContent=state.whitelist.length; $('#mChannels').textContent=state.channels.length;
  $('#followupList').innerHTML=state.followups.length?state.followups.map(x=>`<article><div><h3>${esc(x.title)}</h3><div class="meta">对象：${esc(x.target)} · ${esc(x.method||'未设置方式')} · ${esc(x.cycle||'未设置周期')}</div><p>${esc(x.rule||'暂无补充规则')}</p></div><div class="actions-row"><button onclick="editFollowup('${x.id}')">编辑</button><button class="danger" onclick="removeItem('followups','${x.id}')">删除</button></div></article>`).join(''):'<article><div><h3>还没有单项跟进</h3><p class="meta">新增后会自动创建独立过程文档。</p></div></article>';
  $('#taskList').innerHTML=state.tasks.length?state.tasks.map(x=>`<article><div><h3>${esc(x.title)}</h3><div class="meta">截止：${esc(x.due||'未设置')} · ${esc(x.status)}</div></div><div class="actions-row"><button onclick="editTask('${x.id}')">编辑</button><button class="danger" onclick="removeItem('tasks','${x.id}')">删除</button></div></article>`).join(''):'<article><div><h3>还没有待办</h3></div></article>';
  $('#whiteList').innerHTML=state.whitelist.length?state.whitelist.map(x=>`<article><div><h3>${esc(x.name)}</h3><div class="meta">${esc(x.channel||'未指定平台')} · ${esc(x.identity||'未填写身份 ID')}</div></div><button class="danger" onclick="removeItem('whitelist','${x.id}')">移除</button></article>`).join(''):'<article><div><h3>白名单为空</h3><p class="meta">当前不会对任何联系人自动回复。</p></div></article>';
  const f=$('#settingsForm'); f.ownerName.value=state.config.ownerName||'';f.digestTime.value=state.config.digestTime||'20:00';f.aiLabelEnabled.checked=!!state.config.aiLabelEnabled;f.autoSendEnabled.checked=!!state.config.autoSendEnabled;
}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active')});
const editor=$('#editor'), editorForm=$('#editorForm'); let saveAction=null;
function openEditor(title,fields,action){$('#editorTitle').textContent=title;$('#editorFields').innerHTML=fields;saveAction=action;editor.showModal()}
function openFollowup(x={}){openEditor(x.id?'编辑跟进':'新增跟进',`<label>任务名称<input name="title" required value="${esc(x.title||'')}"></label><label>跟进对象<input name="target" required value="${esc(x.target||'')}"></label><label>跟进方式<input name="method" placeholder="例如：钉钉私聊" value="${esc(x.method||'')}"></label><label>跟进周期<input name="cycle" placeholder="例如：每周一、每 3 天" value="${esc(x.cycle||'')}"></label><label>补充跟进规则<textarea name="rule" placeholder="可自由描述升级条件、话术、截止判断等">${esc(x.rule||'')}</textarea></label><label>状态<select name="status"><option>进行中</option><option ${x.status==='暂停'?'selected':''}>暂停</option><option ${x.status==='已关闭'?'selected':''}>已关闭</option></select></label>`,async d=>api(x.id?`/api/followups/${x.id}`:'/api/followups',{method:x.id?'PUT':'POST',body:JSON.stringify(d)}))}
function editFollowup(id){openFollowup(state.followups.find(x=>x.id===id))}
function openTask(x={}){openEditor(x.id?'编辑待办':'新增待办',`<label>待办内容<input name="title" required value="${esc(x.title||'')}"></label><label>截止时间<input name="due" type="datetime-local" value="${esc(x.due||'')}"></label><label>状态<select name="status"><option>待办</option><option ${x.status==='进行中'?'selected':''}>进行中</option><option ${x.status==='已完成'?'selected':''}>已完成</option></select></label>`,async d=>api(x.id?`/api/tasks/${x.id}`:'/api/tasks',{method:x.id?'PUT':'POST',body:JSON.stringify(d)}))}
function editTask(id){openTask(state.tasks.find(x=>x.id===id))}
function openWhite(){openEditor('新增白名单联系人','<label>姓名<input name="name" required></label><label>沟通平台<select name="channel"><option>钉钉</option><option>企业微信</option><option>飞书</option><option>其他</option></select></label><label>平台身份 ID<input name="identity" placeholder="建议填写稳定 ID，避免同名误发"></label>',async d=>api('/api/whitelist',{method:'POST',body:JSON.stringify(d)}))}
editorForm.onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(editorForm));try{await saveAction(d);editor.close();await load();toast('已保存')}catch(err){toast(err.message)}};
async function removeItem(kind,id){if(!confirm('确认删除？过程文档会保留。'))return;try{await api(`/api/${kind}/${id}`,{method:'DELETE'});await load();toast('已删除')}catch(err){toast(err.message)}}
$('#settingsForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;const d={ownerName:f.ownerName.value,digestTime:f.digestTime.value,aiLabelEnabled:f.aiLabelEnabled.checked,autoSendEnabled:f.autoSendEnabled.checked};if(d.autoSendEnabled&&!confirm('自动外发只对符合白名单和安全策略的消息生效。确认启用？'))return;try{await api('/api/config',{method:'POST',body:JSON.stringify(d)});await load();toast('设置已保存')}catch(err){toast(err.message)}};
load().catch(e=>toast(e.message));
